FROM alpine:edge

MAINTAINER Dmitry Melnichenko <dmytro.i.am@gmail.com>

RUN echo "@testing http://dl-4.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
    apk --update add mongodb@testing && \
    rm -rf /var/cache/apk/*

VOLUME ["/data/db"]

EXPOSE 27017

ENTRYPOINT ["mongod", "--bind_ip",  "0.0.0.0", "--nounixsocket"]
